# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 75b59b585026648c3b4593648351a5cc2a9496cf83c3bc51cacc451aa72cfbc30be76179db05a5f1ce020b0f4be9b8f699f196f9666aef110f42bf983ecdb815

test:
  secret_key_base: 78efd37df218f7268612fdbf3a558ca07ca43cc904b14bf1443efc56b90efbbdab02043ec55146c64fde7f881bf347202b413b4ac75716953c4081d2be67d826

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
